/* Generated By:JavaCC: Do not edit this line. JsonParserJavacc.java */
package com.qunar.base.validator.schema.javacc;

import com.qunar.base.validator.schema.*;
import com.qunar.base.validator.util.StringUnmarshaller;

import java.io.EOFException;
import java.util.ArrayList;
import java.util.List;

@SuppressWarnings("all")
public final class JsonParserJavacc implements JsonParserJavaccConstants {

  final public Schema<Object> parse() throws ParseException {
  Schema<Object> json = null;
  Object o = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
    {if (true) throw new RuntimeException(new EOFException());}
      break;
    case DIGITS:
    case NULL:
    case NAN:
    case INFINITY:
    case BOOLEAN:
    case IDENTIFIER_SANS_EXPONENT:
    case IDENTIFIER_STARTS_WITH_EXPONENT:
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
    case 26:
    case 27:
    case 29:
    case 33:
    case 35:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 26:
        jj_consume_token(26);
        break;
      default:
        jj_la1[0] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        json = onlyAttrValue();
        break;
      case 27:
        json = JsonObject();
        break;
      case 33:
        json = JsonArray();
        break;
      case DIGITS:
      case NULL:
      case NAN:
      case INFINITY:
      case BOOLEAN:
      case IDENTIFIER_SANS_EXPONENT:
      case IDENTIFIER_STARTS_WITH_EXPONENT:
      case SINGLE_QUOTE_LITERAL:
      case DOUBLE_QUOTE_LITERAL:
      case 35:
        json = pureValue();
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    {if (true) return json;}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Schema JsonObject() throws ParseException {
  ObjectRuleSchema o = new ObjectRuleSchema();
  Attr attr = null;
  List<Attr> attrList = new ArrayList<Attr>();
    jj_consume_token(27);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER_SANS_EXPONENT:
    case IDENTIFIER_STARTS_WITH_EXPONENT:
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
      Members(o);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    jj_consume_token(28);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        ;
        break;
      default:
        jj_la1[4] = jj_gen;
        break label_1;
      }
      jj_consume_token(29);
      attr = attr();
                                        attrList.add(attr);
    }
    o.setAttrRule(attrList);
    {if (true) return o;}
    throw new Error("Missing return statement in function");
  }

  final public Attr attr() throws ParseException {
  String name=null;
  List arg=null;
    name = JsonMemberName();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 30:
      arg = arguments();
      break;
    default:
      jj_la1[5] = jj_gen;
      ;
    }
                                              {if (true) return new Attr(name,arg);}
    throw new Error("Missing return statement in function");
  }

  final public List<Object> arguments() throws ParseException {
  List<Object> list = new ArrayList<Object>();
  Object obj;
    jj_consume_token(30);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIGITS:
    case NULL:
    case NAN:
    case INFINITY:
    case BOOLEAN:
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
    case 35:
      obj = argument();
                        list.add(obj);
      break;
    default:
      jj_la1[6] = jj_gen;
      ;
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 31:
        ;
        break;
      default:
        jj_la1[7] = jj_gen;
        break label_2;
      }
      jj_consume_token(31);
      obj = argument();
                                                               list.add(obj);
    }
    jj_consume_token(32);
    {if (true) return list;}
    throw new Error("Missing return statement in function");
  }

  final private Object argument() throws ParseException {
 Object o = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
      o = JsonString();
      break;
    case DIGITS:
    case NAN:
    case INFINITY:
    case 35:
      o = JsonNumber();
      break;
    case BOOLEAN:
      o = JsonBoolean();
      break;
    case NULL:
      o = JsonNull();
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return  o;}
    throw new Error("Missing return statement in function");
  }

  final private Object JsonNull() throws ParseException {
  Token t;
    t = jj_consume_token(NULL);
               {if (true) return null;}
    throw new Error("Missing return statement in function");
  }

  final private void Members(ObjectRuleSchema o) throws ParseException {
    Pair(o);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 31:
      jj_consume_token(31);
      Members(o);
      break;
    default:
      jj_la1[9] = jj_gen;
      ;
    }
  }

  final private void Pair(ObjectRuleSchema o) throws ParseException {
  String property;
  Schema value = new PureValueSchema(new Any());
    property = JsonMemberName();
    jj_consume_token(29);
    value = JsonValue();
    o.addSchema(property, value);
  }

  final private String JsonMemberName() throws ParseException {
  Token t; String value;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER_SANS_EXPONENT:
    case IDENTIFIER_STARTS_WITH_EXPONENT:
      t = Identifier();
                    {if (true) return  String.valueOf(t.image);}
      break;
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
      value = JsonString();
                       {if (true) return value;}
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Schema JsonArray() throws ParseException {
  Attr attr = null;
  List<Attr> attrList = new ArrayList<Attr>();
  ArrayRuleSchema array = new ArrayRuleSchema();
    jj_consume_token(33);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIGITS:
    case NULL:
    case NAN:
    case INFINITY:
    case BOOLEAN:
    case IDENTIFIER_SANS_EXPONENT:
    case IDENTIFIER_STARTS_WITH_EXPONENT:
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
    case 27:
    case 33:
    case 35:
      Elements(array);
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    jj_consume_token(34);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_3;
      }
      jj_consume_token(29);
      attr = attr();
                                             attrList.add(attr);
    }
    array.setAttrRule(attrList);
    {if (true) return array;}
    throw new Error("Missing return statement in function");
  }

  final private void Elements(ArrayRuleSchema array) throws ParseException {
  Schema element;
    element = JsonValue();
                       array.addSchema(element);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 31:
      jj_consume_token(31);
      Elements(array);
      break;
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  final private Schema JsonValue() throws ParseException {
  Schema schema = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DIGITS:
    case NULL:
    case NAN:
    case INFINITY:
    case BOOLEAN:
    case IDENTIFIER_SANS_EXPONENT:
    case IDENTIFIER_STARTS_WITH_EXPONENT:
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
    case 35:
      schema = pureValue();
      break;
    case 27:
      schema = JsonObject();
      break;
    case 33:
      schema = JsonArray();
      break;
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {if (true) return schema;}
    throw new Error("Missing return statement in function");
  }

  final private PureValueSchema onlyAttrValue() throws ParseException {
  Attr attr = null;
  List<Attr> attrList = new ArrayList<Attr>();
    label_4:
    while (true) {
      jj_consume_token(29);
      attr = attr();
                  attrList.add(attr);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_4;
      }
    }
    PureValueSchema schema = new PureValueSchema(new Any());
    schema.setAttrRule(attrList);
    {if (true) return schema;}
    throw new Error("Missing return statement in function");
  }

  final private PureValueSchema pureValue() throws ParseException {
  Attr attr = null;
  Attr attr1 = null;
  List<Attr> attrList = new ArrayList<Attr>();
  Object o = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
      o = JsonString();
      break;
    case DIGITS:
    case NAN:
    case INFINITY:
    case 35:
      o = JsonNumber();
      break;
    case BOOLEAN:
      o = JsonBoolean();
      break;
    case IDENTIFIER_SANS_EXPONENT:
    case IDENTIFIER_STARTS_WITH_EXPONENT:
      attr1 = attr();
      break;
    case NULL:
      o = JsonNull();
      break;
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 29:
        ;
        break;
      default:
        jj_la1[17] = jj_gen;
        break label_5;
      }
      jj_consume_token(29);
      attr = attr();
                                 attrList.add(attr);
    }
    if(attr1!=null)
    {
      o=new Any();
    attrList.add(0,attr1);
  }
    PureValueSchema schema = new PureValueSchema(o);
    schema.setAttrRule(attrList);
    {if (true) return schema;}
    throw new Error("Missing return statement in function");
  }

  final private boolean JsonBoolean() throws ParseException {
  Token t;
    t = jj_consume_token(BOOLEAN);
    {if (true) return Boolean.valueOf(t.image);}
    throw new Error("Missing return statement in function");
  }

  final private Object JsonPrimitive() throws ParseException {
  Object value;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINGLE_QUOTE_LITERAL:
    case DOUBLE_QUOTE_LITERAL:
      value = JsonString();
                          {if (true) return value;}
      break;
    case DIGITS:
    case NAN:
    case INFINITY:
    case 35:
      value = JsonNumber();
                          {if (true) return value;}
      break;
    case BOOLEAN:
      value = JsonBoolean();
                           {if (true) return value;}
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Number JsonNumber() throws ParseException {
  String intpart = null,
         fracpart = null,
         exppart = null;
  Number value;
    if (jj_2_1(2)) {
      value = JsonSpecialNumbers();
                                {if (true) return value;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DIGITS:
      case 35:
        intpart = JsonInt();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 36:
          fracpart = JsonFrac();
          break;
        default:
          jj_la1[19] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case EXPONENT:
          exppart = JsonExp();
          break;
        default:
          jj_la1[20] = jj_gen;
          ;
        }
    Number n;
    if (exppart != null || fracpart != null) {
      fracpart = (fracpart == null) ? "" : fracpart;
      exppart = (exppart == null) ? "" : exppart;
      n = new java.math.BigDecimal(intpart + fracpart + exppart);
    } else {
      n = new java.math.BigDecimal(intpart);
    }
    {if (true) return n;}
        break;
      default:
        jj_la1[21] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final private Number JsonSpecialNumbers() throws ParseException {
  boolean negative = false;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NAN:
      jj_consume_token(NAN);
           {if (true) return Double.NaN;}
      break;
    case INFINITY:
    case 35:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 35:
        jj_consume_token(35);
         negative = true;
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      jj_consume_token(INFINITY);
                                        {if (true) return negative ? Double.NEGATIVE_INFINITY : Double.POSITIVE_INFINITY;}
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private String JsonInt() throws ParseException {
  String digits;
  boolean negative = false;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 35:
      jj_consume_token(35);
         negative = true;
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    digits = Digits();
    if(negative)
      {if (true) return "-" + digits;}
    {if (true) return digits;}
    throw new Error("Missing return statement in function");
  }

  final private String JsonFrac() throws ParseException {
  String digits;
    jj_consume_token(36);
    digits = Digits();
    {if (true) return "." + digits;}
    throw new Error("Missing return statement in function");
  }

  final private String JsonExp() throws ParseException {
  Token t;
    t = jj_consume_token(EXPONENT);
                  {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final private Token Identifier() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER_STARTS_WITH_EXPONENT:
      t = jj_consume_token(IDENTIFIER_STARTS_WITH_EXPONENT);
      break;
    case IDENTIFIER_SANS_EXPONENT:
      t = jj_consume_token(IDENTIFIER_SANS_EXPONENT);
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                                                                            {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  final private String Digits() throws ParseException {
  Token t;
    t = jj_consume_token(DIGITS);
    {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  final private String JsonString() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SINGLE_QUOTE_LITERAL:
      t = jj_consume_token(SINGLE_QUOTE_LITERAL);
      break;
    case DOUBLE_QUOTE_LITERAL:
      t = jj_consume_token(DOUBLE_QUOTE_LITERAL);
      break;
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    String value = StringUnmarshaller.unmarshall(t.image);
    {if (true) return value;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_9()) jj_scanpos = xsp;
    if (jj_scan_token(INFINITY)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(NAN)) return true;
    return false;
  }

  private boolean jj_3R_6() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_7()) {
    jj_scanpos = xsp;
    if (jj_3R_8()) return true;
    }
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(35)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public JsonParserJavaccTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4000000,0x28031fc0,0x2c031fc1,0x31800,0x20000000,0x40000000,0x307c0,0x80000000,0x307c0,0x80000000,0x31800,0x8031fc0,0x20000000,0x80000000,0x8031fc0,0x20000000,0x31fc0,0x20000000,0x30740,0x0,0x20,0x40,0x0,0x300,0x0,0x1800,0x30000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0xa,0xa,0x0,0x0,0x0,0x8,0x0,0x8,0x0,0x0,0xa,0x0,0x0,0xa,0x0,0x8,0x0,0x8,0x10,0x0,0x8,0x8,0x8,0x8,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public JsonParserJavacc(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public JsonParserJavacc(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new JsonParserJavaccTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public JsonParserJavacc(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new JsonParserJavaccTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public JsonParserJavacc(JsonParserJavaccTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JsonParserJavaccTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 27; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private List<int[]> jj_expentries = new ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[37];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 27; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 37; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
